### ISSUE TITLE
Implement ASP servers in cakeml AM.

### ISSUE THREAD

**Issue by ampetz** [ku-sldg/attestation-testbed#30]
Similar in spirit to  `handle_asp_*` handlers from [here](https://github.com/ku-sldg/haskell-am/blob/master/copland-interp/src/ServerHandlers.hs).

cakeml AM JSON libraries [here](https://github.com/ku-sldg/am-cakeml/tree/master/copland/json).

See ASP Request and Response Message JSON schemas documentation [here](https://github.com/ku-sldg/json-am/blob/master/copland_json.pdf).

**Comment by Durbatuluk1701** [comment]
Closing as no longer planned, ASP invocation has taken a very different turn and the servers are no longer necessary
