### ISSUE TITLE
Implement SIG servers in cakeml AM

### ISSUE THREAD

**Issue by ampetz** [ku-sldg/attestation-testbed#31]
Similar in spirit to `handle_sig` handlers from [here](https://github.com/ku-sldg/haskell-am/blob/master/copland-interp/src/ServerHandlers.hs).

cakeml AM JSON libraries [here](https://github.com/ku-sldg/am-cakeml/tree/master/copland/json).

See SIG Request and Response Message JSON schemas documentation [here](https://github.com/ku-sldg/json-am/blob/master/copland_json.pdf).

**Comment by Durbatuluk1701** [comment]
SIG servers are no longer necessary as SIG will be handled by its own ASP. Closing as no longer necessary
