### ISSUE TITLE
Update CakeML AM Copland-related datatypes

### ISSUE THREAD

**Issue by ampetz** [ku-sldg/attestation-testbed#32]
Update cakeml Copland-related datatypes (phrases, evidence, etc.) to be consistent with the Coq datatypes defined [here](https://github.com/ku-sldg/copland-avm/blob/master/src/Term_Defs.v).

Verification-only artifacts like event traces (`Ev` type in Coq) not needed in cakeml.

**Comment by Durbatuluk1701** [comment]
This has been completed as we have over time managed to hoist a great deal of functionality into Coq and these types are no longer in CakeML but extracted
