### ISSUE TITLE
Update CakeML AM with latest CVM and appraisal functionality from Coq.

### ISSUE THREAD

**Issue by ampetz** [ku-sldg/attestation-testbed#33]
Have cakeml AM use latest Copland Virtual Machine and generalized appraisal functions from [here](https://github.com/ku-sldg/copland-avm).

Best option is to extract them via Coq --> CakeML synthesis (see @barclata for latest status on this).  Alternatively, or as a first pass, do manually.

This issue depends on #32 being implemented first.

**Comment by Durbatuluk1701** [comment]
This has been completed many different times
