### ISSUE TITLE
Create a Client AM in Rust

### ISSUE THREAD

**Issue by ampetz** [ku-sldg/attestation-testbed#46]
- [x] Define Copland datatypes in Rust (Copland Terms (only a minimal subset for this subtask), ProtocolRunRequest, ProtocolRunResponse)
- [x] Implement JSON bindings in Rust for above 
- [x] Test a client request/response JSON session against pre-built server AMs
- [x] Finalize Definitions of Copland Datatypes and their JSON Bindings
- [x] Add support for reading in pre-JSONified Copland Terms from files (and incorporating into larger client requests)

**Comment by Durbatuluk1701** [comment]
Closed by commits in https://github.com/ku-sldg/am-clients
