### ISSUE TITLE
Decide on local .INI format/fields

### ISSUE THREAD

**Issue by palexand** [ku-sldg/attestation-testbed#5]
- [ ] Addresses for each AM node
- [ ] Addresses for each ASP
- [ ] Crypto implementations as ASPs
- [ ] Public keys for all participants
- [ ] Golden values for appraisal

**Comment by Durbatuluk1701** [comment]
This is essentially the same as deciding on the Manifest definition, which has been resolved in Copland AVM spec for a while now. Closest PR would likely be ku-sldg/copland-avm#27
