### ISSUE TITLE
Decide on JSON interface for ASPs

### ISSUE THREAD

**Issue by palexand** [ku-sldg/attestation-testbed#9]
- ~~TSS interface~~
- [x] ASP requests
- [x] ASP responses

**Comment by Durbatuluk1701** [comment]
TSS Interface being fixed in #8 

Please review the ASP JSON interface outlined [here](https://github.com/ku-sldg/copland-avm/wiki/Attestation-Manager-Interfaces)
@ampetz @palexand @LoganSchmalz
